repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0 # keep in sync with noxfile!
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
