# @package _global_
---
featurisation:
  featurisation_name: atomic_num_only
  cut_off: 5.0
  which_hydrogens: explicit
  num_proc: 4
  batch_size: 1000
  num_node_feats: 41
  num_edge_feats: 0
  x_features:
    - physicsml_atom_idxs
    - physicsml_atom_numbers
    - physicsml_coordinates
  featurisation_metadata:
    version: 1
    config:
      - column: ligand_pocket_bytes
        representations:
          - name: physicsml_features
            as: "{feature_name}"
            config:
              backend: openeye
              atomic_number_mapping: {1: 0, 4: 1, 5: 2, 6: 3, 7: 4, 8: 5, 9: 6, 11: 7, 12: 8, 14: 9, 15: 10, 16: 11, 17: 12, 19: 13, 20: 14, 23: 15, 25: 16, 26: 17, 27: 18, 28: 19, 29: 20, 30: 21, 33: 22, 34: 23, 35: 24, 38: 25, 42: 26, 44: 27, 45: 28, 48: 29, 51: 30, 52: 31, 53: 32, 70: 33, 75: 34, 76: 35, 77: 36, 78: 37, 79: 38, 80: 39, 0: 40, 67: 40}
